export const loadingWords: string[] = [
  "Compiling code: Coffee break time!",
  "Debugging: A programmer's daily meditation.",
  "Coding in progress... better than watching paint dry!",
  "React components assembling: Like LEGO, but fancier.",
  "Loading... Rome wasn't coded in a day.",
  "Patience is a virtue, especially in coding.",
  "Breathe in, breathe out, and think binary.",
  "Building prototypes: Where imagination meets reality.",
  "Your code is brewing... almost ready!",
  "Remember, every pixel matters.",
  "Crafting your masterpiece, one line at a time.",
  "While you wait, don't forget to hydrate!",
  "Creating your digital canvas...",
  "In code we trust, compiling it... just a must.",
  "Fine-tuning your digital experience.",
  "Hang tight, we're bending the binary.",
  "Prototyping: Where dreams get their wings.",
  "Turning coffee into code...",
  "Your future masterpiece is in the making.",
  "Like a fine wine, good code takes time.",
  "Chill, the semicolons are aligning.",
  "Writing code is easy, it's thinking that's hard.",
  "Good things take time, including bug fixes.",
  "Making the impossible, possible... one byte at a time.",
  "Your patience will be rewarded with pixels.",
  "Code is poetry, currently in composition.",
  "Just like magic, but with more logic.",
  "Crafting experiences, one component at a time.",
  "Software development: Where 'Ctrl + Z' is your friend.",
  "Your dream interface is just a few loops away.",
  "Juggling bits and bytes for perfection.",
  "Engineering your vision into reality.",
  "Making digital dreams come true...",
  "Almost there: Just resolving a few dependencies.",
  "Your app is baking at 350 degrees.",
  "Bridging the gap between idea and reality.",
  "Building the bridge to the digital world.",
  "Code is like humor; when you have to explain it, it's bad.",
  "Innovation in progress... Please stand by."
];
